### ISSUE TITLE
Using a tag as the --rev argument

### ISSUE THREAD

**Issue by acowley** [seppeljordan/nix-prefetch-github#12]
I used to pass tag names in the `--rev` command line argument, but this is no longer working. If I track down the corresponding hash for the tag and use that, `nix-prefetch-github` still works. Using the tag name still works in `fetchFromGitHub`. Here is an example of a failure:

```
$ nix-prefetch-github RadeonOpenCompute ROCm-CompilerSupport --rev roc-2.6.0
Traceback (most recent call last):
  File "/nix/store/bd07n8il3wr9zw8d0h6dkca4i6r4ncha-nix-prefetch-github-2.3/bin/.nix-prefetch-github-wrapped", line 11, in <module>
    sys.exit(_main())
  File "/nix/store/8ls7pdjgrfy309pmg6lqqr5wi8b9m601-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/8ls7pdjgrfy309pmg6lqqr5wi8b9m601-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/8ls7pdjgrfy309pmg6lqqr5wi8b9m601-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/8ls7pdjgrfy309pmg6lqqr5wi8b9m601-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/bd07n8il3wr9zw8d0h6dkca4i6r4ncha-nix-prefetch-github-2.3/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 212, in _main
    output_dictionary = nix_prefetch_github(owner, repo, prefetch, rev)
  File "/nix/store/bd07n8il3wr9zw8d0h6dkca4i6r4ncha-nix-prefetch-github-2.3/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 197, in nix_prefetch_github
    return sync_perform(dispatcher(), main_intent())
  File "/nix/store/alyh38wxqsl18y0cpd0c8nkzsqhf2487-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/_sync.py", line 34, in sync_perform
    six.reraise(*errors[0])
  File "/nix/store/vswrwlavw387mp7cb6z3jrb2vxqbgpz2-python3.7-six-1.12.0/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/nix/store/alyh38wxqsl18y0cpd0c8nkzsqhf2487-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/alyh38wxqsl18y0cpd0c8nkzsqhf2487-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 120, in <lambda>
    return val.on(success=lambda r: _do(r, generator, False),
  File "/nix/store/alyh38wxqsl18y0cpd0c8nkzsqhf2487-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 100, in _do
    val = generator.send(result)
  File "/nix/store/bd07n8il3wr9zw8d0h6dkca4i6r4ncha-nix-prefetch-github-2.3/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 191, in main_intent
    "rev": prefetch_results['rev'],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by seppeljordan** [comment]
Hi,

Thank you for reporting the issue. I will look into this soon-ish. Could you in the meantime post the version of of `nix-prefetch-github` that you are using?

Thanks

**Comment by acowley** [comment]
2.3

**Comment by bsima** [comment]
Similarly, with version 2.2:

```
$ nix-prefetch-github --nix --rev 0.5.4 lins05 slackbot
Traceback (most recent call last):
  File "/nix/store/s8g72f4iry4y8gf37401skw9za6y3apa-nix-prefetch-github-2.2/bin/.nix-prefetch-github-wrapped", line 11, in <module>
    sys.exit(_main())
  File "/nix/store/8cqpibf95abc2wiqk6vdjk9mm2fzgzc8-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/8cqpibf95abc2wiqk6vdjk9mm2fzgzc8-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/8cqpibf95abc2wiqk6vdjk9mm2fzgzc8-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/8cqpibf95abc2wiqk6vdjk9mm2fzgzc8-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/s8g72f4iry4y8gf37401skw9za6y3apa-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 213, in _main
    output_dictionary = nix_prefetch_github(owner, repo, prefetch, rev)
  File "/nix/store/s8g72f4iry4y8gf37401skw9za6y3apa-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 198, in nix_prefetch_github
    return sync_perform(dispatcher(), main_intent())
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/_sync.py", line 34, in sync_perform
    six.reraise(*errors[0])
  File "/nix/store/bs4jw5gkdfa1i8nfk2ikicbac9c9an0q-python3.7-six-1.12.0/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 121, in <lambda>
    error=lambda e: _do(e, generator, True))
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 98, in _do
    val = generator.throw(*result)
  File "/nix/store/s8g72f4iry4y8gf37401skw9za6y3apa-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 187, in main_intent
    rev=rev
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 120, in <lambda>
    return val.on(success=lambda r: _do(r, generator, False),
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 100, in _do
    val = generator.send(result)
  File "/nix/store/s8g72f4iry4y8gf37401skw9za6y3apa-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 164, in prefetch_github
    ).format(owner=owner, repo=repo, output=output)
NameError: name 'output' is not defined
```

**Comment by bsima** [comment]
It seems using the sha instead of the tag doesn't work either

```
$ nix-prefetch-github --nix --rev 7195d46b9e1dc4ecfae0bdcaa91461202689bfe5 lins05 slackbot
Traceback (most recent call last):
  File "/nix/store/s8g72f4iry4y8gf37401skw9za6y3apa-nix-prefetch-github-2.2/bin/.nix-prefetch-github-wrapped", line 11, in <module>
    sys.exit(_main())
  File "/nix/store/8cqpibf95abc2wiqk6vdjk9mm2fzgzc8-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/8cqpibf95abc2wiqk6vdjk9mm2fzgzc8-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/8cqpibf95abc2wiqk6vdjk9mm2fzgzc8-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/8cqpibf95abc2wiqk6vdjk9mm2fzgzc8-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/s8g72f4iry4y8gf37401skw9za6y3apa-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 213, in _main
    output_dictionary = nix_prefetch_github(owner, repo, prefetch, rev)
  File "/nix/store/s8g72f4iry4y8gf37401skw9za6y3apa-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 198, in nix_prefetch_github
    return sync_perform(dispatcher(), main_intent())
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/_sync.py", line 34, in sync_perform
    six.reraise(*errors[0])
  File "/nix/store/bs4jw5gkdfa1i8nfk2ikicbac9c9an0q-python3.7-six-1.12.0/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 121, in <lambda>
    error=lambda e: _do(e, generator, True))
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 98, in _do
    val = generator.throw(*result)
  File "/nix/store/s8g72f4iry4y8gf37401skw9za6y3apa-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 187, in main_intent
    rev=rev
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 120, in <lambda>
    return val.on(success=lambda r: _do(r, generator, False),
  File "/nix/store/3vzb4lc3hx0lj8wwwh9ahg92lx5h9x4j-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 100, in _do
    val = generator.send(result)
  File "/nix/store/s8g72f4iry4y8gf37401skw9za6y3apa-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 164, in prefetch_github
    ).format(owner=owner, repo=repo, output=output)
NameError: name 'output' is not defined
```
