### ISSUE TITLE
Please propagate error messages from subprocesses

### ISSUE THREAD

**Issue by deliciouslytyped** [seppeljordan/nix-prefetch-github#40]
NOTE: for someone coming here to find out how to use nix-prefetch-github in a pure shell:
```
nix-shell -I nixpkgs=channel:nixos-unstable --pure -p git cacert nix nix-prefetch-github --run "env NIX_PATH=$NIX_PATH nix-prefetch-github OWNER REPO"
```

Please do something about propagating errors from internal exec calls.

Running `nix-prefetch-github` in a `--pure` shell causes `nix-build` to fail with:
```
$ nix-shell -I nixpkgs=channel:nixos-unstable --pure -p cacert git nix nix-prefetch-github --run "nix-prefetch-github WikidPad WikidPad"
Internal Error: Calculate hash value for sources in github repo WikidPad/WikidPad.
```

The style of the `nix-prefetch-github` code is not typical, and appears more difficult to debug than usual.
I imagine most issues are with the environment, and not the code, so propagating information from exec-ed binaries, and their calling arguments, would probably cover most issues, and reporters could diagnose things themselves.

There are several specific problems as you go through the paces of constructing the command:
## missing git
```
$ nix-shell -I nixpkgs=channel:nixos-unstable --pure -p nix-prefetch-github --run "nix-prefetch-github WikidPad WikidPad" > master.json
Traceback (most recent call last):          
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/bin/.nix-prefetch-github-wrapped", line 9, in <module>
    sys.exit(main())             
  File "/nix/store/2hdbkrisr351wry8cgh791kdx9mp11z5-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 829, in __call__                                                
    return self.main(*args, **kwargs) 
  File "/nix/store/2hdbkrisr351wry8cgh791kdx9mp11z5-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 782, in main          
    rv = self.invoke(ctx)               
  File "/nix/store/2hdbkrisr351wry8cgh791kdx9mp11z5-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 1066, in invoke                                                 
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/2hdbkrisr351wry8cgh791kdx9mp11z5-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)            
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/__main__.py", line 42, in main
    prefetched_repository = nix_prefetch_github(                                                                       
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/public.py", line 20, in nix_prefetch_github
    return perform_effects(                                                                                            
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/effects.py", line 215, in perform_effects
    return sync_perform(dispatcher(), effects)
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_sync.py", line 31, in sync_perform
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_sync.py", line 31, in sync_perform
    raise errors[0]
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_base.py", line 71, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 119, in <lambda>
    error=lambda e: _do(e, generator, True),
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 96, in _do
    val = generator.throw(result)
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/core/prefetch.py", line 38, in prefetch_github
    yield self._detect_revision()
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_base.py", line 71, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 119, in <lambda>
    error=lambda e: _do(e, generator, True),
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 96, in _do
    val = generator.throw(result)
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/core/prefetch.py", line 64, in _detect_revision
    actual_rev = yield self._revision_index.get_revision_from_name(
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_base.py", line 71, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 119, in <lambda>
    error=lambda e: _do(e, generator, True),
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 96, in _do
    val = generator.throw(result)
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/core/revision.py", line 13, in get_revision_from_name
    list_remote = yield Effect(GetListRemote(repository=self._repository))
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_sync.py", line 69, in sync_wrapper
    box.succeed(f(*pass_args, **kwargs))
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/effects.py", line 50, in _performer
    return sync_perform(dispatcher, effect(intent))
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_sync.py", line 31, in sync_perform
    raise errors[0]
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_base.py", line 71, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 119, in <lambda>
    error=lambda e: _do(e, generator, True),
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 96, in _do
    val = generator.throw(result)
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/effects.py", line 145, in get_list_remote_performer
    returncode, stdout = yield Effect(
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_sync.py", line 69, in sync_wrapper
    box.succeed(f(*pass_args, **kwargs))
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/effects.py", line 203, in execute_command_performer
    process_return = subprocess.run(
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```
This is fine, because it tells you what the problem is.

## missing cacert
```
$ nix-shell -I nixpkgs=channel:nixos-unstable --pure -p git nix-prefetch-github --run "nix-prefetch-github WikidPad WikidPad" > master.json
Could not find a public repository named 'WikidPad' for user 'WikidPad' at github.com
```
This is not ok, but from experience one may know that `cacert` is missing.

## missing nix-build
```
$ nix-shell -I nixpkgs=channel:nixos-unstable --pure -p cacert git nix-prefetch-github --run "nix-prefetch-github WikidPad WikidPad" > master.json
Traceback (most recent call last):                 
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/bin/.nix-prefetch-github-wrapped", line 9, in <module>   
    sys.exit(main())
  File "/nix/store/2hdbkrisr351wry8cgh791kdx9mp11z5-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs) 
  File "/nix/store/2hdbkrisr351wry8cgh791kdx9mp11z5-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 782, in main    
    rv = self.invoke(ctx)                   
  File "/nix/store/2hdbkrisr351wry8cgh791kdx9mp11z5-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/2hdbkrisr351wry8cgh791kdx9mp11z5-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 610, in invoke                                               
    return callback(*args, **kwargs)
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/__main__.py", line 42, in main
    prefetched_repository = nix_prefetch_github(
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/public.py", line 20, in nix_prefetch_github        
    return perform_effects(         
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/effects.py", line 215, in perform_effects
    return sync_perform(dispatcher(), effects)  
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_sync.py", line 31, in sync_perform
    raise errors[0]                                                                                                    
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_base.py", line 71, in guard
    return (False, f(*args, **kwargs))                                                                                 
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 119, in <lambda>
    error=lambda e: _do(e, generator, True),
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 96, in _do
    val = generator.throw(result)
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/core/prefetch.py", line 39, in prefetch_github
    yield self._calculate_sha256_sum()
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_base.py", line 71, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 119, in <lambda>
    error=lambda e: _do(e, generator, True),
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 96, in _do
    val = generator.throw(result)
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/core/prefetch.py", line 80, in _calculate_sha256_sum
    self._calculated_hash = yield Effect(
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_sync.py", line 69, in sync_wrapper
    box.succeed(f(*pass_args, **kwargs))
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/effects.py", line 50, in _performer
    return sync_perform(dispatcher, effect(intent))
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_sync.py", line 31, in sync_perform
    raise errors[0]
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_base.py", line 71, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 119, in <lambda>
    error=lambda e: _do(e, generator, True),
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 96, in _do
    val = generator.throw(result)
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/effects.py", line 159, in calculate_sha256_sum
    return_code, nix_output = yield Effect(
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_sync.py", line 69, in sync_wrapper
    box.succeed(f(*pass_args, **kwargs))
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/effects.py", line 50, in _performer
    return sync_perform(dispatcher, effect(intent))
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_sync.py", line 31, in sync_perform
    raise errors[0]
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_base.py", line 71, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 119, in <lambda>
    error=lambda e: _do(e, generator, True),
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/do.py", line 96, in _do
    val = generator.throw(result)
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/effects.py", line 136, in try_prefetch_performer
    result = yield Effect(
  File "/nix/store/qxrjjv7i4w6s1iivxblzqwjw2c2pa0l8-python3.8-effect-1.1.0/lib/python3.8/site-packages/effect/_sync.py", line 69, in sync_wrapper
    box.succeed(f(*pass_args, **kwargs))
  File "/nix/store/v7zha1cmv3rmi6j6b7s6ys630pcax62s-python3.8-nix-prefetch-github-4.0.3/lib/python3.8/site-packages/nix_prefetch_github/effects.py", line 203, in execute_command_performer
    process_return = subprocess.run(
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/4s0h5aawbap3xhldxhcijvl26751qrjr-python3-3.8.9/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nix-build'

```
This is once again fine because it says `nix-build` is missing.

## missing NIX_PATH
```
$ nix-shell -I nixpkgs=channel:nixos-unstable --pure -p cacert git nix nix-prefetch-github --run "nix-prefetch-github WikidPad WikidPad" > master.json
Internal Error: Calculate hash value for sources in github repo WikidPad/WikidPad.
```
This is not OK because it's entirely invisible what the problem is.

## debugging note:
By running strace one can find the output, but I'm only listing this post-ex-facto after I already found what I was looking for by breakpointing using `pudb` (https://github.com/inducer/pudb/issues/405#issuecomment-865246281) and running `nix-build` with the appropriate arguments (e.g. `ExecuteCommand(command=(["nix-build", nix_filename, "--no-out-link"]))` -> `nix-build /run/user/1000/tmp_lm4y7hj/prefetch-github.nix --no-out-link`) :
```
$ nix-shell -I nixpkgs=channel:nixos-unstable --pure -p cacert git nix nix-prefetch-github strace --run "strace -v -s 1000 -f -e execve,read,write nix-prefetch-github WikidPad WikidPad"  |& less
...
[pid 21851] <... read resumed>"error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at /run/user/1000/tmpk3rwjqu8/prefetch-github.nix:2:17\n", 8192) = 146
```

**Comment by seppeljordan** [comment]
@deliciouslytyped Thank you for the thorough bug bug report. I tried to address the issue per commit https://github.com/seppeljordan/nix-prefetch-github/commit/dc3daca9d89027877570fa7103f3b16e193f87e8

I am pretty sure that with this change stderr of subprocesses is printed to stderr. Using the current changeset I was able to produce the following output:

```
$ nix-shell --pure --run "nix-prefetch-github WikidPad WikidPad"
warning: Git tree '/home/me/nix-prefetch-github' is dirty
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing setuptools-check-hook
Executing setuptoolsShellHook
Obtaining file:///home/me/nix-prefetch-github
    Preparing wheel metadata ... done
Requirement already satisfied: attrs in /nix/store/hmr5wz58f5qc8dw7v4l53yj1ah2rpq7k-python3.8-attrs-20.3.0/lib/python3.8/site-packages (from nix-prefetch-github==4.0.3) (20.3.0)
Requirement already satisfied: effect in /nix/store/1ccj5fxwnm7737xv3z2jbm0g9lzqk1x5-python3.8-effect-1.1.0/lib/python3.8/site-packages (from nix-prefetch-github==4.0.3) (1.1.0)
Requirement already satisfied: click in /nix/store/diazka9p575lw1vxy3x39xcjqpq74gp2-python3.8-click-7.1.2/lib/python3.8/site-packages (from nix-prefetch-github==4.0.3) (7.1.2)
Installing collected packages: nix-prefetch-github
  Running setup.py develop for nix-prefetch-github
Successfully installed nix-prefetch-github
WARNING: You are using pip version 21.0.1; however, version 21.1.3 is available.
You should consider upgrading via the '/nix/store/q6gfck5czr67090pwm53xrdyhpg6bx67-python3-3.8.9/bin/python3.8 -m pip install --upgrade pip' command.
Finished executing setuptoolsShellHook
fatal: unable to access 'https://github.com/WikidPad/WikidPad.git/': SSL certificate problem: unable to get local issuer certificate

ExecuteCommand(command=['git', 'ls-remote', '--symref', 'https://github.com/WikidPad/WikidPad.git'], cwd=None, merge_stderr=False, environment_variables={'GIT_ASKPASS': '', 'GIT_TERMINAL_PROMPT': '0'}) failed with returncode 128.
```

Please let me know, if you find this an adequate solution for this issue. I will release a new version of `nix-prefetch-github` and request a merge to `nixpkgs` after this issue can be closed.

**Comment by seppeljordan** [comment]
Since no feedback is given I assume that this is resolved for the OP.
