### ISSUE TITLE
How it supposed to work?

### ISSUE THREAD

**Issue by Pitometsu** [seppeljordan/nix-prefetch-github#8]
```
nix-shell -p nix gitMinimal nix-prefetch-github -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable-small.tar.gz --pure --run 'nix-prefetch-github --nix --rev refs/heads/nixos-unstable nixos nixpkgs'
```
```
Traceback (most recent call last):
  File "/nix/store/w4j2paga2c32fks9viwr06l4m12accg4-nix-prefetch-github-2.2/bin/.nix-prefetch-github-wrapped", line 11, in <module>
    sys.exit(_main())
  File "/nix/store/jl77hjkh5xmg41v74iyj34hrfp84j41i-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/jl77hjkh5xmg41v74iyj34hrfp84j41i-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/nix/store/jl77hjkh5xmg41v74iyj34hrfp84j41i-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/jl77hjkh5xmg41v74iyj34hrfp84j41i-python3.7-click-7.0/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/w4j2paga2c32fks9viwr06l4m12accg4-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 213, in _main
    output_dictionary = nix_prefetch_github(owner, repo, prefetch, rev)
  File "/nix/store/w4j2paga2c32fks9viwr06l4m12accg4-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 198, in nix_prefetch_github
    return sync_perform(dispatcher(), main_intent())
  File "/nix/store/nnxyvqfvd073fj4hhgflvms5jajnm6rn-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/_sync.py", line 34, in sync_perform
    six.reraise(*errors[0])
  File "/nix/store/468n8kmifbp5nwbgz4r91ivnwxsnz9cc-python3.7-six-1.12.0/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/nix/store/nnxyvqfvd073fj4hhgflvms5jajnm6rn-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/nnxyvqfvd073fj4hhgflvms5jajnm6rn-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 121, in <lambda>
    error=lambda e: _do(e, generator, True))
  File "/nix/store/nnxyvqfvd073fj4hhgflvms5jajnm6rn-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 98, in _do
    val = generator.throw(*result)
  File "/nix/store/w4j2paga2c32fks9viwr06l4m12accg4-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 187, in main_intent
    rev=rev
  File "/nix/store/nnxyvqfvd073fj4hhgflvms5jajnm6rn-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/_base.py", line 78, in guard
    return (False, f(*args, **kwargs))
  File "/nix/store/nnxyvqfvd073fj4hhgflvms5jajnm6rn-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 120, in <lambda>
    return val.on(success=lambda r: _do(r, generator, False),
  File "/nix/store/nnxyvqfvd073fj4hhgflvms5jajnm6rn-python3.7-effect-0.12.0/lib/python3.7/site-packages/effect/do.py", line 100, in _do
    val = generator.send(result)
  File "/nix/store/w4j2paga2c32fks9viwr06l4m12accg4-nix-prefetch-github-2.2/lib/python3.7/site-packages/nix_prefetch_github/__init__.py", line 164, in prefetch_github
    ).format(owner=owner, repo=repo, output=output)
NameError: name 'output' is not defined
```

**Comment by seppeljordan** [comment]
Hi,

`nix-shell -p nix gitMinimal nix-prefetch-github -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable-small.tar.gz --pure --run 'nix-prefetch-github --nix --rev nixos-unstable NixOS nixpkgs'`
should work.  Notice how I changed the `--rev` argument.
